version:  "3.9"

services:

  myapp:
    container_name: tweet-sentiment-analysis
    image: ezeparziale/tweet-sentiment-analysis
    env_file:
      - .env
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile